<?php

namespace Troulite\PathfinderBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Troulite\PathfinderBundle\Entity\ClassDefinition;
use Troulite\PathfinderBundle\Entity\ClassSpell;

/**
 * ClassSpellRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ClassSpellRepository extends EntityRepository
{
    /**
     * Find a class spell by name and class
     *
     * @param string $name
     * @param ClassDefinition $class
     *
     * @return ClassSpell|null
     */
    public function findByNameAndClass($name, ClassDefinition $class)
    {
        $query = 'SELECT cs FROM TroulitePathfinderBundle:ClassSpell cs LEFT JOIN cs.spell s WHERE s.name = :name AND cs.class = :cid';

        return $this->_em->createQuery($query)->setParameters([
            'name' => $name,
            'cid'  => $class->getId(),
        ])->getSingleResult();
    }
}
