<?php

namespace Troulite\PathfinderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClassDefinitionRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ClassDefinitionRepository extends EntityRepository
{
}
